CREATE TABLE Person
(
    person_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(50) UNIQUE NOT NULL,
    birthday  VARCHAR(4) NOT NULL
);

CREATE TABLE Book
(
    book_id      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id    INTEGER,
    book_name    VARCHAR(50) NOT NULL,
    author_name  VARCHAR(50) NOT NULL,
    birthday VARCHAR(4) NOT NULL,
    FOREIGN KEY (person_id) REFERENCES Person (person_id) ON DELETE SET NULL
);

INSERT INTO Person (name, birthday)
VALUES ('Name1', '1991'),
       ('Name2', '1983'),
       ('Name3', '1991'),
       ('Name4', '1988'),
       ('Name5', '1992'),
       ('Name6', '1959');


INSERT INTO Book (book_name, person_id, author_name, birthday)
VALUES ('book1', 1, 'author1', '1991'),
       ('book2', 1, 'author2', '1992'),
       ('book3', 3, 'author3', '1993'),
       ('book4', 2, 'author4', '1994');