CREATE DATABASE library;

DROP DATABASE IF EXISTS library;

CREATE TABLE IF NOT EXISTS person
(
    person_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(50) UNIQUE,
    birthday  DATE
);

CREATE TABLE IF NOT EXISTS book
(
    book_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id INTEGER,
    book_name VARCHAR(50),
    author_name VARCHAR(50),
    release_date DATE,
    FOREIGN KEY (person_id) REFERENCES person(person_id)
);